#!/bin/sh
# postinst script for sleepi3-firmware
#
# see: dh_installdeb(1)

set -e

OVERLAY=sleepi3
CONFIG_FILE=/boot/firmware/config.txt
OLD_CONFIG_FILE=/boot/config.txt

case "$1" in
    configure)
        if dpkg --compare-versions "$2" lt "2.0.0"; then
            if [ -f $CONFIG_FILE ]; then
                raspi-config nonint do_i2c 0
                raspi-config nonint set_config_var core_freq 250 $CONFIG_FILE
                if ! grep -q -E "^(device_tree_|dt)overlay=${OVERLAY}" $CONFIG_FILE; then
                    if config=$(grep -E "^(device_tree_|dt)overlay=${OVERLAY}" $OLD_CONFIG_FILE); then
                        printf "${config}" >> $CONFIG_FILE
                    else
                        printf "dtoverlay=${OVERLAY}\n" >> $CONFIG_FILE
                    fi
                fi
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
