#!/bin/sh
# postinst script for sleepi3-firmware
#
# see: dh_installdeb(1)

set -e

OVERLAY=sleepi3
CONFIG=/boot/firmware/config.txt
CONFIG_OLD=/boot/config.txt

case "$1" in
    configure)
        if dpkg --compare-versions "$2" lt "2.0.0"; then
            if [ ! -h $CONFIG_OLD ]; then
                if [ -e $CONFIG ]; then
                    echo "create backup $CONFIG.old of $CONFIG"
                    cp $CONFIG $CONFIG.old
                fi
                mv $CONFIG_OLD $CONFIG
                ln -s $CONFIG $CONFIG_OLD
            fi
        fi
        if [ -e $CONFIG ]; then
            raspi-config nonint do_i2c 0
            raspi-config nonint set_config_var core_freq 250 $CONFIG
            if ! grep -q -E "^(device_tree_|dt)overlay=${OVERLAY}" $CONFIG; then
                printf "dtoverlay=${OVERLAY}\n" >> $CONFIG
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
